name: Maven Build and Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v5

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y zstd

    - name: Set up Java and Maven
      uses: actions/setup-java@v5
      with:
        distribution: zulu
        java-version: 25
        cache: maven

    - name: Build with Maven
      run: mvn -B verify

  deploy:
    name: Deploy to Central Portal
    needs: [build]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v5

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y zstd

    - name: Set up Java and Maven
      uses: actions/setup-java@v5
      with:
        distribution: zulu
        java-version: 25
        cache: maven
        server-id: central
        server-username: MAVEN_CENTRAL_USERNAME
        server-password: MAVEN_CENTRAL_PASSWORD
        gpg-private-key: ${{ secrets.gpg_private_key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Publish Maven package
      run: mvn -B -Pcentral-deploy deploy -DskipTests
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
        MAVEN_CENTRAL_USERNAME: ${{ secrets.central_username }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.central_password }}
